version: '3.11'

services:
  electronic_sales_network:

    build:
      context: .

    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    tty: false

    volumes:
      - .:/electronic_sales_network

    restart: on-failure

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on: [database]

  database:
    image: postgres:15.3-alpine

    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data_electronic_sales_network:/var/lib/postgresql/data

volumes:
  postgres_data_electronic_sales_network:
  electronic_sales_network_api:
  database:
    driver: local